version: '3'


services:
  rabbitmq:
    image: "rabbitmq:3-management"
    volumes:
      - ./rabbitmq-dev.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password rabbitmq
      - FLASK_APP=app.py
      
  
  mongo:
    image: mongo:latest
    ports:
       - 27017:27017

  flask_mailer:
    build:
      context: flask_mailer/
    depends_on:
      - rabbitmq
      - mongo
    environment:
      # ...
    ports:
      - 5000:5000
